run only integration test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -349,112 +349,112 @@ jobs:
           path: |
             test-app/build/reports/gordonError
             test-app/build/reports/gordonNormal
-  jacoco_report:
-    name: Generate Combined JaCoCo Coverage Report
-    runs-on: ubuntu-latest
-    needs: [ test, integration_test ]
-
-    steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v4.2.2
-
-      - name: Setup Common Environment
-        uses: ./.github/actions/setup-environment
-
-      - name: Download Unit Test Results (for coverage)
-        uses: actions/download-artifact@v5
-        with:
-          name: unit-test-results
-          path: .
-
-      - name: Download Integration Test Results (for coverage)
-        uses: actions/download-artifact@v5
-        with:
-          name: integration-test-results
-          path: .
-
-      - name: List files to verify download (optional debugging)
-        run: |
-          echo "Listing downloaded unit test coverage data structure:"
-          find . -name "*.exec" -type f
-          echo "Listing downloaded integration test coverage data structure:"
-          find . -name "*.ec" -type f
-          echo "Listing contents of example-app/example-app-data/build/outputs:"
-          ls -R example-app/example-app-data/build/outputs || echo "Path not found"
-          echo "Listing contents of build/outputs (root):" # For aggregated report context
-          ls -R build/outputs || echo "Path not found"
-
-
-      - name: Generate Combined JaCoCo Report
-        run: ./gradlew jacocoAggregatedReport
-
-      - name: Upload JaCoCo Report
-        uses: actions/upload-artifact@v4.6.2
-        with:
-          name: jacoco-aggregated-report
-          path: build/reports/jacoco/jacocoAggregatedReport/html/
-          if-no-files-found: error
-          retention-days: 7
-  sonarcloud_analysis:
-    name: SonarCloud Analysis
-    runs-on: ubuntu-latest
-    needs: jacoco_report
-    steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v4.2.2
-
-      - name: Setup Common Environment
-        uses: ./.github/actions/setup-environment
-
-      - name: Cache SonarCloud packages
-        uses: actions/cache@v4
-        with:
-          path: ~/.sonar/cache
-          key: ${{ runner.os }}-sonar
-          restore-keys: ${{ runner.os }}-sonar
-
-      - name: Cache Gradle packages
-        uses: actions/cache@v4
-        with:
-          path: |
-            ~/.gradle/caches
-            ~/.gradle/wrapper
-          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
-          restore-keys: |
-            ${{ runner.os }}-gradle-
-
-      - name: Grant execute permission for gradlew
-        run: chmod +x ./gradlew
-
-      - name: Run SonarCloud Analysis
-        run: ./gradlew sonar \
-          -Dsonar.host.url=https://sonarcloud.io \
-          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
-          -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
-          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
-          -Dsonar.pullrequest.key=${{ github.event.pull_request.number }} \
-          -Dsonar.pullrequest.branch=${{ github.event.pull_request.head.ref }} \
-          -Dsonar.pullrequest.base=${{ github.event.pull_request.base.ref }} \
-          -Dsonar.scm.revision=${{ github.sha }}
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-  publish:
-    name: Release build and publish
-    runs-on: macOS-latest
-    needs: sonarcloud_analysis
-    steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v4.2.2
-
-      - name: Setup Common Environment
-        uses: ./.github/actions/setup-environment
-
-      - name: Publish to MavenCentral
-        # replace with publishAndReleaseToMavenCentral when everything works as expected
-        run: ./gradlew publishToMavenCentral --no-configuration-cache
-        env:
-          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
-          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
-          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
-          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
-          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY_CONTENTS }}
+#  jacoco_report:
+#    name: Generate Combined JaCoCo Coverage Report
+#    runs-on: ubuntu-latest
+#    needs: [ test, integration_test ]
+#
+#    steps:
+#      - name: Checkout Repository
+#        uses: actions/checkout@v4.2.2
+#
+#      - name: Setup Common Environment
+#        uses: ./.github/actions/setup-environment
+#
+#      - name: Download Unit Test Results (for coverage)
+#        uses: actions/download-artifact@v5
+#        with:
+#          name: unit-test-results
+#          path: .
+#
+#      - name: Download Integration Test Results (for coverage)
+#        uses: actions/download-artifact@v5
+#        with:
+#          name: integration-test-results
+#          path: .
+#
+#      - name: List files to verify download (optional debugging)
+#        run: |
+#          echo "Listing downloaded unit test coverage data structure:"
+#          find . -name "*.exec" -type f
+#          echo "Listing downloaded integration test coverage data structure:"
+#          find . -name "*.ec" -type f
+#          echo "Listing contents of example-app/example-app-data/build/outputs:"
+#          ls -R example-app/example-app-data/build/outputs || echo "Path not found"
+#          echo "Listing contents of build/outputs (root):" # For aggregated report context
+#          ls -R build/outputs || echo "Path not found"
+#
+#
+#      - name: Generate Combined JaCoCo Report
+#        run: ./gradlew jacocoAggregatedReport
+#
+#      - name: Upload JaCoCo Report
+#        uses: actions/upload-artifact@v4.6.2
+#        with:
+#          name: jacoco-aggregated-report
+#          path: build/reports/jacoco/jacocoAggregatedReport/html/
+#          if-no-files-found: error
+#          retention-days: 7
+#  sonarcloud_analysis:
+#    name: SonarCloud Analysis
+#    runs-on: ubuntu-latest
+#    needs: jacoco_report
+#    steps:
+#      - name: Checkout Repository
+#        uses: actions/checkout@v4.2.2
+#
+#      - name: Setup Common Environment
+#        uses: ./.github/actions/setup-environment
+#
+#      - name: Cache SonarCloud packages
+#        uses: actions/cache@v4
+#        with:
+#          path: ~/.sonar/cache
+#          key: ${{ runner.os }}-sonar
+#          restore-keys: ${{ runner.os }}-sonar
+#
+#      - name: Cache Gradle packages
+#        uses: actions/cache@v4
+#        with:
+#          path: |
+#            ~/.gradle/caches
+#            ~/.gradle/wrapper
+#          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
+#          restore-keys: |
+#            ${{ runner.os }}-gradle-
+#
+#      - name: Grant execute permission for gradlew
+#        run: chmod +x ./gradlew
+#
+#      - name: Run SonarCloud Analysis
+#        run: ./gradlew sonar \
+#          -Dsonar.host.url=https://sonarcloud.io \
+#          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
+#          -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
+#          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
+#          -Dsonar.pullrequest.key=${{ github.event.pull_request.number }} \
+#          -Dsonar.pullrequest.branch=${{ github.event.pull_request.head.ref }} \
+#          -Dsonar.pullrequest.base=${{ github.event.pull_request.base.ref }} \
+#          -Dsonar.scm.revision=${{ github.sha }}
+#        env:
+#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#  publish:
+#    name: Release build and publish
+#    runs-on: macOS-latest
+#    needs: sonarcloud_analysis
+#    steps:
+#      - name: Checkout Repository
+#        uses: actions/checkout@v4.2.2
+#
+#      - name: Setup Common Environment
+#        uses: ./.github/actions/setup-environment
+#
+#      - name: Publish to MavenCentral
+#        # replace with publishAndReleaseToMavenCentral when everything works as expected
+#        run: ./gradlew publishToMavenCentral --no-configuration-cache
+#        env:
+#          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
+#          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
+#          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
+#          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
+#          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY_CONTENTS }}
